apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: ejercicio-leccion-5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ejercicio-leccion-5
  template:
    metadata:  
      labels:
        app: ejercicio-leccion-5
    spec:
      containers:
      - name: ejercicio-leccion-5
        image: bastianmoral/ejercicio-leccion-5
        ports:
        - containerPort: 80
