apiVersion: v1
kind: Service
metadata:
  name: servicio-prueba-leccion-5
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30000
  selector:
    app: ejercicio-leccion-5
  